#! /usr/bin/env bash

WSROOT="${BASH_SOURCE[0]}"

if [ "${WSROOT#/}" = "$WSROOT" ]; then
    WSROOT="$(pwd)/${BASH_SOURCE[0]}"
fi

WSROOT="${WSROOT%/.x-cmd/*}"

# print "$WSROOT"
if [ "$#" -gt 0 ]; then
    op="$1"
    shift
    # echo "$WSROOT/dev/unstable/$op"
    rm -rf "$WSROOT/src/$op"
    mv -f "$WSROOT/dev/unstable/$op" "$WSROOT/src/"
fi